export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const GET_PRODTUCT_LIST_REQUEST = "GET_PRODTUCT_LIST_REQUEST";
export const GET_PRODTUCT_LIST_SUCCESS = "GET_PRODTUCT_LIST_SUCCESS";
export const GET_PRODTUCT_LIST_FAILURE = "GET_PRODTUCT_LIST_FAILURE";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";

export const ADD_TO_FAV_REQUEST = "ADD_TO_FAV_REQUEST";
export const ADD_TO_FAV_SUCCESS = "ADD_TO_FAV_SUCCESS";
export const ADD_TO_FAV_FAILURE = "ADD_TO_FAV_FAILURE";

export const REMOVE_FROM_FAV_REQUEST = "REMOVE_FROM_FAV_REQUEST";
export const REMOVE_FROM_FAV_SUCCESS = "REMOVE_FROM_FAV_SUCCESS";
export const REMOVE_FROM_FAV_FAILURE = "REMOVE_FROM_FAV_FAILURE";

export const COMMON_SORT_ORDER_CHANGE = "COMMON_SORT_ORDER_CHANGE";
export const COMMON_PROD_FILTER_CHANGE = "COMMON_PROD_FILTER_CHANGE";

export const ON_PURCHASE_ORDER_REQUEST = "ON_PURCHASE_ORDER_REQUEST";
export const ON_PURCHASE_ORDER_SUCCESS = "ON_PURCHASE_ORDER_SUCCESS";
export const ON_PURCHASE_ORDER_FAILURE = "ON_PURCHASE_ORDER_FAILURE";

export const USER_AUTO_LOGIN_REQUEST = "USER_AUTO_LOGIN_REQUEST";
export const USER_AUTO_LOGIN_SUCCESS = "USER_AUTO_LOGIN_SUCCESS";
export const USER_AUTO_LOGIN_FAILURE = "USER_AUTO_LOGIN_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const USER_UPDATE_CART_COUNT = "USER_UPDATE_CART_COUNT";

// Actions to update user data on login/logout
export const SET_USER_CART = "SET_USER_CART";
export const SET_USER_CARDS = "SET_USER_CARDS";
export const SET_USER_ORDERS = "SET_USER_ORDERS";
export const SET_USER_FAV_LIST = "SET_USER_FAV_LIST";
export const SET_USER_ADDRESSES = "SET_USER_ADDRESSES";
